server:
  port: 8090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: activity  # ??? ??? ?????? ??
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activiey-log-server-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
#        "org.example.booknote.activity.domain.Activity, org.example.booknotelogserver.booknotelogserver.activity.domain"



kakfa:
  topic:
    activity: activity-log-topic
