server:
  port: 8090
spring:
  data:
    mongodb:
      host: ${MONGODB_URL}
      port: ${MONGODB_PORT}
      database: activity
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      group-id: activiey-log-server-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
#        "org.example.booknote.activity.domain.Activity, org.example.booknotelogserver.booknotelogserver.activity.domain"



kakfa:
  topic:
    activity: activity-log-topic
